### ISSUE TITLE
Change LEDs on keypress

### ISSUE THREAD

**Issue by VerosK** [FFY00/logitechd#3]
Hallo @FFY00,

I've run into this project while looking for drivers for managing LEDs on Logitech G815.

I'm looking for daemon which can change LEDs on my keyboard on some external events.

I understand that this project is currently Work In Progress (TM), but I would like to know if this project the code I'm looking for?

**Comment by FFY00** [comment]
It would be, yes. We will provide a CLI for you to change the colors and then you can write a script to integrate this with the external events you are talking about.

However, https://github.com/libratbag/libratbag also does this and it actually works right now :smile:. I've started `logitechd` because `libratbag` is very limiting, as it is vendor agnostic, and can't implement all Logitech specific features. But for your use-case it should work just fine.

**Comment by VerosK** [comment]
Thank you very much for your answer.

I will give libratbag a second try.

I think would like to do some not se easy tasks which libratnag is unable to handle (at the moment).

Examples:
 * dim LEDs under numeric keys when NumLock is off
 * run red flash on keyboard when monitoring is down
 * run green flash when some long running tasks finishes.

**Comment by FFY00** [comment]
libratbag only provides a way for you to interact with the device, you will have to implement all this integrations yourself. It will be the same here.

**Comment by VerosK** [comment]
I understand that I have to check the source events (like finishing the long task). But I still haven't found a way in libratbag how to perform action on the keyboard (like short green flash on LEDs).

This is the task I wasn't able to do and I hoped it will be implemented in logitechd in some future day.

**Comment by FFY00** [comment]
Ah, ok. That will be implemented here. The hope is for everything the device allows us to do, to be exported by `logitechd`.

**Comment by VerosK** [comment]
Thank you very much for clarification.

Staying tuned.
